### ISSUE TITLE
Random crash around the letter T in album view

### ISSUE THREAD

**Issue by func0der** [adneal/Apollo-CM#20]
Hey there,

if I scroll down with the scrollbar on the right side Apollo randomly crashes.
Music is still playing, but the App closes down. 
This happens around the letter T of my albums. 

I could not find any logs or something, to put in here, but maybe you could provide me with a location for them so I can attach them?

Greetings
func0der

**Comment by func0der** [comment]
Is there anyone maintaining this Repo or should I better report to Cyanogenmod?

**Comment by adneal** [comment]
The CM repo is much more active. Also, I think this has already been reported JIRA. It'll be fixed soon.

**Comment by func0der** [comment]
Thanks for the information. :D
