### ISSUE TITLE
Toggle display of album art and last.fm images

### ISSUE THREAD

**Issue by ehcloninger** [adneal/Apollo-CM#7]
I would like see a toggle preference that allows me to remove the tiled display of album art and last.fm images in the artist and album fragments. These images convey little useful information for me and I would prefer to just see a list of names in larger text for easier viewing in a car dock.

This would also affect the Now Playing fragment, where the album art would be replaced with large text displaying the artist, album, track name and track number. 

I'm adding this function in my fork, but curious if there is interest in committing the change back.

**Comment by adneal** [comment]
Hmm. I wasn't planning to add different ways to view the lists in the CM version, at least not right away. I understand the need for a better UI when is comes to a car dock or simply driving and holding your phone. I've considered adding a "Driving mode" you can toggle that would basically make things more friendly to use in the car. If I merge your commits, then that would leave the CM version with one preference that toggles the artist/album images, and I would rather not have that one preference only. I say keep it your fork and in the meantime I'll work out a better way to use the app in your car.

**Comment by ehcloninger** [comment]
OK. I'm still playing with it, so I don't have anything to give yet anyway. It's just a side project. 

If you look in my public repo for pfdock, you'll find an app that handles the car dock intent. Feel free to ask questions about it.
