### ISSUE TITLE
Covers from local folders

### ISSUE THREAD

**Issue by pseiler** [adneal/Apollo-CM#9]
Hi,

I'd like to have a feature that it scanns the folders where the tracks lies for Cover files like Cover.jpg and Cover.png. When I rip a CD I always download a high resolution Cover for it and place it in the same directory. Apollo only search for low resolution Covers from last.fm. Please implement a function that it search first for local Covers and then search on last.fm. The Local (high resolution) Cover Image should be preffered displaying

**Comment by ragusa87** [comment]
Very good idea ! It can be very useful !
